"""Add destination info fields to Trip model

Revision ID: 03fd16e064e1
Revises: 2491eb2a7b66
Create Date: 2025-04-18 15:49:23.690092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fd16e064e1'
down_revision = '2491eb2a7b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('destination_display_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('destination_country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('destination_country')
        batch_op.drop_column('destination_display_name')
        batch_op.drop_column('destination_info')

    # ### end Alembic commands ###
